# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 04:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('kd_bank', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_bank', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BuktiTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekening_pengirim', models.CharField(max_length=50)),
                ('bank_pengirim', models.CharField(max_length=50)),
                ('waktu_transfer', models.DateTimeField(default=datetime.datetime.now)),
                ('rekening_penerima', models.CharField(max_length=50)),
                ('gambar_bukti', models.ImageField(upload_to='image/bukti')),
                ('bank_penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('waktu_cart', models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False)),
                ('total_pembelian', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Harga',
            fields=[
                ('tanggal_harga', models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False)),
                ('harga', models.IntegerField(default=0)),
                ('keterangan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='listCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pesan', models.IntegerField(default=0)),
                ('total_harga_peritem', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('kode_pesanan', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama_pemesan', models.CharField(max_length=100)),
                ('no_telp', models.CharField(max_length=100)),
                ('tanggal_pesanan', models.DateTimeField(default=datetime.datetime.now)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Customer')),
                ('waktu_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=100)),
                ('jenis_produk', models.CharField(max_length=20)),
                ('spesifikasi1', models.CharField(max_length=100)),
                ('spesifikasi2', models.CharField(max_length=100)),
                ('spesifikasi3', models.CharField(max_length=100)),
                ('spesifikasi4', models.CharField(max_length=100)),
                ('spesifikasi5', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPengiriman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('ongkir', models.IntegerField(default=0)),
                ('keterangan', models.CharField(max_length=200)),
                ('bukti_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.BuktiTransfer')),
                ('kd_pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Pesanan')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(default=0)),
                ('gambar', models.ImageField(upload_to='image/produk')),
                ('kode_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Produk')),
            ],
        ),
        migrations.CreateModel(
            name='Warna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_warna', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='kode_warna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Warna'),
        ),
        migrations.AddField(
            model_name='listcart',
            name='id_produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Produk'),
        ),
        migrations.AddField(
            model_name='listcart',
            name='waktu_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Cart'),
        ),
        migrations.AddField(
            model_name='harga',
            name='kode_produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Produk'),
        ),
        migrations.AddField(
            model_name='cart',
            name='id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Customer'),
        ),
        migrations.AddField(
            model_name='buktitransfer',
            name='kd_pesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Pesanan'),
        ),
    ]
