# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-16 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghtelectroniccenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=120)),
                ('alamat', models.CharField(max_length=200)),
            ],
        ),
    ]
