# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-01-04 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghtelectroniccenter', '0002_orang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makan',
            fields=[
                ('kd_makan', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_makanan', models.CharField(max_length=120)),
            ],
        ),
    ]
