# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-01-04 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghtelectroniccenter', '0003_makan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkuMakan',
            fields=[
                ('id_aku', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('kd_makan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Makan')),
            ],
        ),
    ]
