# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-01-06 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghtelectroniccenter', '0005_menu_menuhaskandungan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuhaskandungan',
            name='id_menu',
            field=models.ForeignKey(db_column='id_menu', on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Menu'),
        ),
    ]
