# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-01-06 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghtelectroniccenter', '0006_auto_20170106_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblMenu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nama_menu', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMenuDetail',
            fields=[
                ('id_menu_detail', models.AutoField(primary_key=True, serialize=False)),
                ('kandungan', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_menu_detail',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='akumakan',
            name='kd_makan',
        ),
        migrations.RemoveField(
            model_name='buktitransfer',
            name='bank_penerima',
        ),
        migrations.RemoveField(
            model_name='buktitransfer',
            name='kd_pesanan',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='id_customer',
        ),
        migrations.RemoveField(
            model_name='harga',
            name='kode_produk',
        ),
        migrations.RemoveField(
            model_name='listcart',
            name='id_produk',
        ),
        migrations.RemoveField(
            model_name='listcart',
            name='waktu_cart',
        ),
        migrations.RemoveField(
            model_name='menuhaskandungan',
            name='id_menu',
        ),
        migrations.DeleteModel(
            name='Orang',
        ),
        migrations.RemoveField(
            model_name='pesanan',
            name='id_customer',
        ),
        migrations.RemoveField(
            model_name='pesanan',
            name='waktu_cart',
        ),
        migrations.RemoveField(
            model_name='statuspengiriman',
            name='bukti_transfer',
        ),
        migrations.RemoveField(
            model_name='statuspengiriman',
            name='kd_pesanan',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='kode_produk',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='kode_warna',
        ),
        migrations.DeleteModel(
            name='AkuMakan',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='BuktiTransfer',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Harga',
        ),
        migrations.DeleteModel(
            name='listCart',
        ),
        migrations.DeleteModel(
            name='Makan',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuHasKandungan',
        ),
        migrations.DeleteModel(
            name='Pesanan',
        ),
        migrations.DeleteModel(
            name='Produk',
        ),
        migrations.DeleteModel(
            name='StatusPengiriman',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Warna',
        ),
    ]
